# **Introduction to Numpy**

In [7]:
import numpy as np



## Producing a 3D array

In [12]:
np3d = np.array([[1,2,3,4,5,6],[65,53,32,234,65,6],[12312,12312,312312,123123,12321,312312]])
type(np3d)

numpy.ndarray

## Produce an array with zeros in the given dimension (5x5)

In [13]:
np2DNull = np.zeros((5,5))
np2DNull

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Produce an array at the given dimension with the specified value[lin

In [16]:
np2dFull = np.full((10,10), 77)

type(np2dFull)

numpy.ndarray

## **Arange Function**

Produces an array from the given range index from X (including) to the index Y (excluding) with an increasement/decreasement of Z


---


Eg. array = np.array(start, end, +-z)

In [22]:
n1Arange = np.arange(10,50,11)
n1Arange


array([10, 21, 32, 43])

## Produce an array in the given range with the length of len

In [60]:
n1RandomIntArray = np.random.randint(1,101,100)
n1RandomIntArray


array([ 61,  95,   2,  67,   6,  73,  78,  12,  35,  84,  62,  37,  91,
        69,  54,  23,  69,  89,  89,   4,  65,  72,  61,  31,  65,  50,
         4,  65,  16,  48,  18,  80,  50,  99,  83,  70,  39,  99,  47,
        25,  86,  88,  65,  28,  65,   7,  94,  84,  66,  29,  89,  42,
        87,  13,  60,  70,  95,  95,  47,  78,  18,  56,  98,  97,  96,
        79,  84,  31,  58,  92,  61,  27,  53,  84,  30,  26,  87,  64,
        92,  26,  58,  58, 100,  72,  36,   1,  92,  50,  62,  72,  14,
        65,  62,  66,  31,  52,  18,  86,  98,  27])

## Manipulate the array to change shapes

An array is made with 3 rows and 2 columns.
That shape is reversed by the editing the shape attribute, making it 2 columns and 3 rows. Reversing the shape does not make [1,2,3] appear all in one column but rather skipping one value and taking the next one. Like [1,3,5] shown below.

In [66]:
n1ShapeArray = np.array([[1,2,3],[4,5,6]])
print(n1ShapeArray)
n1ShapeArray.shape = (3,2)
print("\n", n1ShapeArray)

[[1 2 3]
 [4 5 6]]

 [[1 2]
 [3 4]
 [5 6]]
